### ISSUE TITLE
Help: Need someone to write About Milestone 4

### ISSUE THREAD

**Issue by DmytroLyt** [MIT-Emerging-Talent/2024-group-11-cdsp#40]
A document : 
- describing our target
audience
- their capabilities and
constraints
- their problem is that we are
addressing
-how we intend to reach
them
- and why they should “hire” us.

**Comment by DmytroLyt** [comment]
Feel free to add something from you

**Comment by MajorPrestige** [comment]
Firstly we need to complete work with milestones 2 and 3, to start the last one.
