### ISSUE TITLE
Group 11 and Group 12 Project Reviewing

### ISSUE THREAD

**Issue by MajorPrestige** [MIT-Emerging-Talent/2024-group-11-cdsp#64]
**Answer the following questions:**

Repository Organization
- Does the main README provide a clear overview of the project’s background and objectives?
- Does the main README tell a clear and coherent story about the research project including motivations, challenges, doubts and ideas for further research?
- Is the main README overwhelmingly long and detailed?
- Does the main README help you navigate the repository?
- Is it easy to find what your way around their repository by reading the names of folders and files?
- Does every folder have a README describing what the folder is used for and what files/folders you will find in there?
- Does it appear as though they have used their repository to collaborate and develop their work, not simply to publish their finished deliverables?
 
Collaboration Documents
- Are all of the collaboration documents complete and written in well-formatted markdown?
- If you were to join this team, how helpful would these documents be for your onboarding?
- Do you see an alignment between the group’s learning objectives and the activity in the repository?
- Has the group clearly identified their constraints, and do these constraints align with the work you see in the rest of the repository?
- When you look through the repository, issues, pull requests and project board, does it appear as though the group follows their own norms?

Domain, Problem Statement and Research Question(s)
- Can you find a clear problem statement that positions their work in an existing domain?
- Is it apparent that the problem statement comes from their personal experience, or another personal motivation/interest?
- Is there evidence that the group has done background research in their problem domain?
- Is there evidence of deeper analysis into the problem and its domain? This could involve systems thinking.
- Are the research questions clearly grounded in the domain and problem statement?
- If there is more than one research question, are they closely related? Or do they point in all different directions?
- Are the research questions specific and actionable - would you be able to tell if you found an answer to the question? and can you imagine how you might start searching for an answer?
 
Retrospectives
- Do the retrospectives help you understand the process, decisions, mistakes, and dynamics behind what is in the repository?
- Does the retrospective focus on behaviors, not individuals?
- Do the retrospectives provide clear and actionable steps the group can take to improve in the future?
- Do the retrospectives contain specific behaviors the group wants to stop doing in the future?
- Can you see evidence in the repository the the group actually applied these changes in their work?
 
Data Sets
- Are the data sets clearly documented in a markdown file?
- Does the non-technical data documentation show an understanding of how the data was collected, and what biases or other problems may exist in the data?
- Does the group discuss which data they were looking for but could not find?
- Is there a discussion of which data modeling choices the group made and why? Including pros and cons for the selected approach?
- Does the non-technical data documentation help you understand why this data is helpful for their project, how they decided these variables are important for modeling their problem?
- Does the technical data documentation help you understand the rows, columns and types?
- Does the technical documentation explain how the group cleaned, reshaped, merged and otherwise modified their data sets to create their final data model?
 
Data Analysis
- Are the scripts/notebooks documented in a markdown file explaining the purpose of each script/notebook and why it’s important for the project?
- Is there a discussion of which data analysis choices the group made and why? Including pros and cons for the selected approach?
- Do the scripts/notebooks run without error? (after installing dependencies)
- Are the scripts/notebooks clearly written so it’s possible to read through them and understand what they are doing? (not necessarily every detail, the big ideas are enough)
- Can you find a markdown file with a non-technical explanation of the analysis results in a markdown file that explains what they learned so far? Does it include sources of uncertainty, doubt and suggestions of further research?

**Comment by DmytroLyt** [comment]
Hello. When we can look for some results of this task?

**Comment by AnnaShliapkina** [comment]
https://docs.google.com/spreadsheets/d/1Q8uZnyZrxt2oyo0R6ipNzFu6vo60uPYRyOgKgOFNTmo/edit#gid=906352181 Here is review for this task
